### ISSUE TITLE
打开显示就闪退

### ISSUE THREAD

**Issue by wuquanzhao** [Liuhaixv/Goose_Goose_Duck_Hack#1]

**Comment by Liuhaixv** [comment]
目前还在开发中，功能会逐步添加，但是我这边没遇到闪退问题，可以用cmd打开下程序看看闪退前有什么报错提示吗？

**Comment by Liuhaixv** [comment]
我知道问题了，我忘记在程序退出前暂停程序了，稍后我更新下

**Comment by Liuhaixv** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.1_fix
