### ISSUE TITLE
迷雾可以加个开关吗

### ISSUE THREAD

**Issue by tuoluo348** [Liuhaixv/Goose_Goose_Duck_Hack#10]
做为一个挂逼隔着墙看着别人感觉好奇怪，能不能加个热键来开关这个迷雾。然后我觉得fps低很有可能跟这个迷雾有关系。

**Comment by Liuhaixv** [comment]
好，那个帧率降低的问题我也注意到了，好像是因为我移除战争迷雾的时候把视野调的有点过大了所以才卡的。我会看看能不能优化下设置。热键的话到时候会添加开关

**Comment by Liuhaixv** [comment]
关于fps低的问题已经发布了新的版本修复
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.3.3

**Comment by FrozenFish259** [comment]
![image](https://user-images.githubusercontent.com/49237108/211688630-89c3972c-f1ad-4383-b8fa-ac6a384b06c2.png)
