### ISSUE TITLE
发现个关于无cd的bug：多键位特殊角色使用无cd无效，反而还增加了很多CD

### ISSUE THREAD

**Issue by 5m17h** [Liuhaixv/Goose_Goose_Duck_Hack#107]
发现个关于无cd的bug：多键位的特殊角色使用无cd失效，反而还增加了很多CD

有一局选了个隐身者鸭子，该角色有2个按键：【shift】隐身    【空格】杀人

结果我勾选了移除技能冷却时间，竟然【空格】杀人 功能的冷却时间变成了300多秒，震惊。

然后我反复勾选【移除技能冷却时间】才小概率把 【空格】杀人 功能冷却功能恢复好，才能杀人。。。

我的推论：特殊角色的移除冷却功能并没用，虽然显示300秒，实则等到正在的冷却好了才能【空格】杀人

**Comment by FrozenFish259** [comment]
测试过普通鸭子是可以无cd连续杀人的

**Comment by FrozenFish259** [comment]
可能是由于技能鸭子特殊？

**Comment by FrozenFish259** [comment]
我刚才用隐身鸭子测试过了，无法复现你说的bug，功能正常运作

**Comment by FrozenFish259** [comment]
#121

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.4.1
