### ISSUE TITLE
可以请教一下怎么找的基地址吗

### ISSUE THREAD

**Issue by 204065248** [Liuhaixv/Goose_Goose_Duck_Hack#110]
如题

**Comment by FrozenFish259** [comment]
用CE开启Mono功能，搜类名找到类的Class地址，然后搜Class地址就能找到唯一的静态变量基址

**Comment by 204065248** [comment]
为啥我的Ce开启mono后，里面没内容呢

**Comment by FrozenFish259** [comment]
![image](https://user-images.githubusercontent.com/49237108/212536708-96b6f09d-4b56-4711-b876-cb8ebc61e105.png)

**Comment by 204065248** [comment]
哦哦，我看的是另一个，吃完饭看看这个有没有

**Comment by 204065248** [comment]
![image](https://user-images.githubusercontent.com/17307843/212541950-9cad345d-5c22-4a74-9c4b-980a3228887f.png)
w
我这里是空的。。，请问一下你是怎么搞的

**Comment by FrozenFish259** [comment]
Search

**Comment by 204065248** [comment]
这个我知道，主要是我里面没有内容，全是空的。这个也是空的
![image](https://user-images.githubusercontent.com/17307843/212542035-8da8fc55-9426-45f1-900e-2049b3cce289.png)

**Comment by FrozenFish259** [comment]
没遇到过，用最新版7.4试试

**Comment by 204065248** [comment]
新版的可以，谢了

**Comment by 204065248** [comment]
我这样操作应该没问题吧
![image](https://user-images.githubusercontent.com/17307843/212542669-c9a90c05-eee9-440d-98fa-19f583c4ebe5.png)
但是结果是0 - -

**Comment by 204065248** [comment]
我知道怎么找基址了，但是我疑惑的是为什么正确的数据还是得不到玩家指针呢
![image](https://user-images.githubusercontent.com/17307843/212543424-a10fa652-ea38-453f-adb6-e9ce2de6d605.png)

**Comment by FrozenFish259** [comment]
正常，说明搜索指针链的途中读到了0值或者就是读取的内存地址非法
