### ISSUE TITLE
你好，下载好后该如何运行呢 

### ISSUE THREAD

**Issue by ShakeWeLy** [Liuhaixv/Goose_Goose_Duck_Hack#113]
所有的调试我都运行了一边但是都没有效果 希望作者能百忙之中解答一下

**Comment by FrozenFish259** [comment]
什么调试

**Comment by FrozenFish259** [comment]
Release里的吗？

**Comment by ShakeWeLy** [comment]
就是运行哪个文件。。。

**Comment by ShakeWeLy** [comment]
下载好您的代码后

**Comment by ShakeWeLy** [comment]
![image](https://user-images.githubusercontent.com/108676217/212544409-4490fb2e-28a6-47c8-af22-5ab11227abd9.png)

**Comment by ShakeWeLy** [comment]
![image](https://user-images.githubusercontent.com/108676217/212544431-ed848d7e-5e6e-4f9f-a665-652c8e152f98.png)

**Comment by FrozenFish259** [comment]
打开sln项目解决方案编译Release x64

**Comment by FrozenFish259** [comment]
或者用发行版https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases

**Comment by ShakeWeLy** [comment]
已解决 感谢您
