### ISSUE TITLE
[Help]Missing map BlackSwan 目前黑天鹅地图缺失

### ISSUE THREAD

**Issue by FrozenFish259** [Liuhaixv/Goose_Goose_Duck_Hack#120]
Need help finding BlackSwan map's image
我找不到黑天鹅的图片资源，有原版图片资源的可以发在这里

**Comment by lanting200** [comment]
![Uploading 1.jpg…]()

**Comment by lanting200** [comment]
![1](https://user-images.githubusercontent.com/42830954/212638068-3c37c973-2375-4d10-a7a7-257da60ccc1f.jpg)
