### ISSUE TITLE
[Bug] Remove cooldown not working correctly with some special roles 移除技能CD冷却在某些角色中存在BUG

### ISSUE THREAD

**Issue by bailijerry** [Liuhaixv/Goose_Goose_Duck_Hack#121]
开了无冷却 然后刀了一个人 在按空格没反应了

**Comment by FrozenFish259** [comment]
刚才测试过普通鸭子杀人CD移除功能正常工作

**Comment by FrozenFish259** [comment]
你是使用的带有技能的鸭子吗？

**Comment by FrozenFish259** [comment]
#107

**Comment by bailijerry** [comment]
连环杀手  杀得不是目标
第一次击杀正常 第二次的时候无论是按空格 还是点按键都没反应了 但是击杀键上并没有提示冷却数字

**Comment by FrozenFish259** [comment]
这就说得通了，连环杀手的技能逻辑是击杀非目标后延长冷却，我会去检查下问题

**Comment by pangjiea** [comment]
星界行者无cd出现bug，无法终止灵魂出窍，无法回到身体当中

**Comment by FrozenFish259** [comment]
> 星界行者无cd出现bug，无法终止灵魂出窍，无法回到身体当中

有意思

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.4.1
