### ISSUE TITLE
死亡快照还会保留上一局的信息，导致重复出现名字

### ISSUE THREAD

**Issue by melody942** [Liuhaixv/Goose_Goose_Duck_Hack#126]

**Comment by z1417992710** [comment]
对这个确实有，死亡快照会保留其他时候的信息，到最后乱套了。。。

**Comment by FrozenFish259** [comment]
提供下复现步骤，游戏模式

**Comment by melody942** [comment]
经典模式，游戏开始新的一局后，点击死亡快照，图上会同时出现这一局和上一局的任务位置

**Comment by FrozenFish259** [comment]
@melody942 就是说上一局游戏和这局的新游戏的死亡玩家重复显示位置了吗？同一局游戏有没有这个问题?

**Comment by melody942** [comment]
对的，同一个人两局的死亡快照会重复。同一局一个玩家只死一次，所以应该没有这个问题。

**Comment by FrozenFish259** [comment]
> 对的，同一个人两局的死亡快照会重复。同一局一个玩家只死一次，所以应该没有这个问题。

好的，我会根据你提供的信息去测试下

**Comment by wsxdc123456** [comment]
对的，刚刚游玩也发现了同样问题

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.3.4
