### ISSUE TITLE
无cd bug

### ISSUE THREAD

**Issue by 5m17h** [Liuhaixv/Goose_Goose_Duck_Hack#131]
隐形鸭子 只能shift隐形一次，之后所有的几轮都不能shift隐私，shift按键按烂了都隐身不了，而且我反复勾选无CD功能的勾都么用！

无CD反而把隐身后面的次数都改没了，一局游戏只能隐形一次。

**Comment by 5m17h** [comment]
还有炸弹鸭子，貌似炸弹有CD，我不能传完炸弹后再传一个，必须等真实的CD好才能传，而图标显示CD已经好是本地假的

**Comment by jixishi** [comment]
炸弹是肯定不行的
那个倒计时应该是数据同步的

**Comment by FrozenFish259** [comment]
> 隐形鸭子 只能shift隐形一次，之后所有的几轮都不能shift隐私，shift按键按烂了都隐身不了，而且我反复勾选无CD功能的勾都么用！
> 
> 无CD反而把隐身后面的次数都改没了，一局游戏只能隐形一次。

有测试过隐身鸭隐身时长吗？

**Comment by 5m17h** [comment]
> > 隐形鸭子只能shift隐形一次，之后所有的几轮都不能shift隐私，shift按键按炸了都隐身没有了，而且我反复勾选无CD功能的勾都没有用！
> > 无CD反而把隐藏身后的次数都改了，一级游戏只能隐藏一次。
> 
> 有测试过隐身鸭隐身时间长吗？

经测试，开了软件后，用隐身鸭子按了shift隐身后只能隐身5秒左右，之后所有轮数都不能再按shift来隐身，相当于一个房间的游戏有且仅能施放一次，非常宝贵的技能。

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.4.1
