### ISSUE TITLE
游戏更新后，新版本的辅助无法使用

### ISSUE THREAD

**Issue by pangjiea** [Liuhaixv/Goose_Goose_Duck_Hack#134]

**Comment by pangjiea** [comment]
[v0.6.3.4.1](https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.3.4.1)无法使用，[v0.6.3.4](https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.3.4)版本可以使用

**Comment by FrozenFish259** [comment]
更新游戏试下

**Comment by pangjiea** [comment]
正确的，一针见血的，我没有更新，最新的辅助是可用的
