### ISSUE TITLE
[BUG] x新版本游戏启动后获取不到运行状态

### ISSUE THREAD

**Issue by jixishi** [Liuhaixv/Goose_Goose_Duck_Hack#135]
![image](https://user-images.githubusercontent.com/57534147/212816925-3b89300c-66ac-4e0a-b073-205872ea2a69.png)

**Comment by wsxdc123456** [comment]
作者老哥休息去了，hack能运作吗？

**Comment by jixishi** [comment]
不行

**Comment by FrozenFish259** [comment]
你游戏应该是管理员权限运行的

**Comment by jixishi** [comment]
电脑重启，游戏重启，然后这个重启我都试过了，不能获取到游戏状态。

**Comment by FrozenFish259** [comment]
辅助权限要高于或等于游戏运行权限

**Comment by jixishi** [comment]
之前都正常，我同样的启动方式。

**Comment by jixishi** [comment]
刚刚试了一下，辅助以管理员启动正常了。
