### ISSUE TITLE
关于当前版本编译bug

### ISSUE THREAD

**Issue by ShuqinZ** [Liuhaixv/Goose_Goose_Duck_Hack#138]
您好作者，想请教一下当前1月17日的版本，是无法正常编译的吗？
在编译过程中报错：
Error (active)	E0028	expression must have a constant value
D:\Entertainment\Goose_Goose_Duck_Hack\Data\offsets.hpp	112	
请问该如何解决？ 感谢并期待您的回复。

**Comment by FrozenFish259** [comment]
用最新C++语言特性支持，Release x64编译

**Comment by ShuqinZ** [comment]
好的十分感谢
