### ISSUE TITLE
为什么把文件删了啊，作者是不打算更新了吗

### ISSUE THREAD

**Issue by RollXo** [Liuhaixv/Goose_Goose_Duck_Hack#147]

**Comment by FrozenFish259** [comment]
谢谢提醒，不小心改到什么设置了....现在开了

**Comment by RollXo** [comment]
地图功能好像有bug，经常刷不出来地图，可以修复一下吗

Liuhaixv ***@***.***> 于2023年1月18日周三 14:11写道：

**Comment by FrozenFish259** [comment]
@RollXo 具体是什么表现呢？

**Comment by RollXo** [comment]
[image: image.png]

Liuhaixv ***@***.***> 于2023年1月18日周三 14:19写道：

**Comment by FrozenFish259** [comment]
邮件看不到图片和附件的

**Comment by RollXo** [comment]
地图没有显示。界面是黑的

Liuhaixv ***@***.***> 于2023年1月18日周三 14:22写道：

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/discussions/148
