### ISSUE TITLE
Additional issues and functionality recommendations that have not yet been resolved

### ISSUE THREAD

**Issue by wooper714** [Liuhaixv/Goose_Goose_Duck_Hack#16]
Thank you for making a great program!
This program will be tested in real-world games and will let you know any issues and suggestions that have not yet been resolved.

[Asking for a solution]
1. When the lights go out, or when the sandstorm blows, nothing is seen.
2. If a duck uses transparentization, it cannot see its name.

[Contents]
1. How about having all players have a border to solve the above problem?
2. If that happens, the player's location will be visible even if the name is not visible, hiding, or hiding in an object.
3. What if I added a function to switch to the viewer's or the dead's view? Then I'll know other people's jobs even if I don't die.

May blessings and good luck be with you!

**Comment by bailijerry** [comment]
nice idea
