### ISSUE TITLE
请问自动完成任务怎么使用

### ISSUE THREAD

**Issue by RollXo** [Liuhaixv/Goose_Goose_Duck_Hack#161]
在任务界面外或任务之中点击按钮都没有反应，点击右侧的说明和秘密菜单选项还会卡顿

**Comment by FrozenFish259** [comment]
开发中，功能还没出

**Comment by Squirrelble** [comment]
多久完善任务

**Comment by FrozenFish259** [comment]
目前功能已经测试可行，能够实现，下个版本将实装。

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.7
