### ISSUE TITLE
[新功能]计划添加大地图玩家信息绘制

### ISSUE THREAD

**Issue by FrozenFish259** [Liuhaixv/Goose_Goose_Duck_Hack#169]
计划在使用TAB打开地图后，在游戏地图上直接绘制玩家信息。
同时，关闭游戏内地图后自动取消绘制

**Comment by cnxxz2333** [comment]
我win7调过设置，这种透明窗口会直接显示成黑色。所以我用不了透视，可能也用不了这个。希望在新功能添加时顺便在主菜单上添加功能开关，允许用户自由选择开启关闭，这样的体验会好很多，谢谢作者大大了。

**Comment by FrozenFish259** [comment]
@cnxxz2333 有ESP的开关的，在秘密菜单

**Comment by cnxxz2333** [comment]
@Liuhaixv 知道，只是希望每个新功能都允许自由开关

**Comment by cnxxz2333** [comment]
别的没什么

**Comment by FrozenFish259** [comment]
已在Mod中实现
