### ISSUE TITLE
关于自动完成任务+自动准备刷币

### ISSUE THREAD

**Issue by jixishi** [Liuhaixv/Goose_Goose_Duck_Hack#179]

**Comment by jixishi** [comment]
可考虑一页一页

**Comment by zeyusmart** [comment]
这个好人一秒结束 坏人才会卡没

**Comment by jixishi** [comment]
建议按键单次一页

**Comment by jixishi** [comment]
速度快的没币的

**Comment by FrozenFish259** [comment]
那是任务被你做完了，不是bug，没有速度快没币的说法

**Comment by FrozenFish259** [comment]
![ZNNR` @E6@{XV~FYQ DJ$JI](https://user-images.githubusercontent.com/49237108/214026309-decc6898-b3b6-4a99-9075-f6605591fe46.png)

**Comment by FrozenFish259** [comment]
除非你在投票的时候做任务，会没有币，这个是测试过的。你听到有声音就是有币

**Comment by FrachSee** [comment]
确实  作者写的和其他人的不一样    他的完成是不会卡币的 代码很出色

**Comment by FrachSee** [comment]
<img width="1255" alt="6b73b81f11ae61c775562a676b11970" src="https://user-images.githubusercontent.com/123346956/214026568-58dbc831-6895-4ff5-83a0-57cb6918c58f.png">

**Comment by mhcms** [comment]
建议加个自动准备

**Comment by jixishi** [comment]
![image](https://user-images.githubusercontent.com/57534147/214027050-4e592dc9-fd3d-472c-b1c7-e191c1f1c5ac.png)
没有结束

**Comment by jixishi** [comment]
我f1 f2连按多次可正常结束

**Comment by FrozenFish259** [comment]
@jixishi 人多的话16个人房，以轮抽模式为准（任务最多）需要3个人做完自己的所有任务才会结束

**Comment by jixishi** [comment]
> @jixishi 人多的话16个人房，以轮抽模式为准（任务最多）需要3个人做完自己的所有任务才会结束

ok谢谢解惑作者大大np

**Comment by FrozenFish259** [comment]
@jixishi 人越多任务越多，多找几个人一起刷最快

**Comment by zeyusmart** [comment]
有没有人一起

**Comment by jixishi** [comment]
f1会呼出帮助信息这个怎么关掉啊
吐了

**Comment by mhcms** [comment]
F1 自动刷任务开一次就好，有任务会自动完成，不用一直开关

**Comment by zeyusmart** [comment]
> f1会呼出帮助信息这个怎么关掉啊 吐了
开一次不关就行

**Comment by FrozenFish259** [comment]
已添加自动准备功能
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.4.6

**Comment by mhcms** [comment]
> 已添加自动准备功能 https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.4.6

太棒了

**Comment by FrozenFish259** [comment]
大家多拉点人来收藏项目，现在卖挂的太猖狂了
![XNS3_~ H7 YS9@O7KC@(UT](https://user-images.githubusercontent.com/49237108/214030568-471b8464-9d8c-4aa4-b78a-930229539898.jpg)

**Comment by mhcms** [comment]
> 大家多拉点人来收藏项目，现在卖挂的太疯狂了 ![XNS3_~ H7 YS9@O7KC@(UT](https://user-images.githubusercontent.com/49237108/214030568-471b8464-9d8c-4aa4-b78a-930229539898.jpg)

已经在好几个辅助论坛看到这个项目的帖子了:)

**Comment by cnxxz2333** [comment]
> 大家多拉点人来收藏项目，现在卖挂的太猖狂了 ![XNS3_~ H7 YS9@O7KC@(UT](https://user-images.githubusercontent.com/49237108/214030568-471b8464-9d8c-4aa4-b78a-930229539898.jpg)
做大做强，再创辉煌！正义开源，薄纱卖挂佬！

**Comment by pangjiea** [comment]
确实离谱，刚有个人10块钱想卖我这个项目

**Comment by canshall** [comment]
有刷币声音但是币没有增加

**Comment by canshall** [comment]
开始游戏后启动右边有弹出已找到，但是对局结束后代币并没有增加。昨天还是可以正常使用的，今天是更新了吗？

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.7
