### ISSUE TITLE
[Feature]Show players that were near killed player 添加新功能: 显示死亡玩家附近的玩家

### ISSUE THREAD

**Issue by wuquanzhao** [Liuhaixv/Goose_Goose_Duck_Hack#18]

**Comment by wuquanzhao** [comment]
身份显示的话可以做个断线重连估计就可以解决

**Comment by Liuhaixv** [comment]
感谢提供建议

**Comment by pangjiea** [comment]
是的，我认为这个功能是推理的核心

**Comment by pangjiea** [comment]
仅靠本轮是否出刀判断出刀人是不准确的，死亡玩家附近玩家的功能可以提高推理的便捷性

**Comment by FrozenFish259** [comment]
谢谢提供建议，这个功能已被计划添加

**Comment by FrozenFish259** [comment]
功能计划：
1. UI完善，高亮死亡玩家
2. 鼠标移动到死亡玩家行时，弹出新的表格，显示死亡时附近小范围的所有玩家，按照距离死亡玩家的距离升序排列
4. 保留局内玩家数据，游戏结束后再刷新玩家列表（防止中途退出游戏，导致数据丢失）
