### ISSUE TITLE
其他优化

### ISSUE THREAD

**Issue by Cuiyim** [Liuhaixv/Goose_Goose_Duck_Hack#182]
在我尝试多开  至少5个账号刷活动币时

我尝试挂机

可否添加  房主自动开始游戏

自动点击   你是否正在游戏弹窗   我想挂机刷活动币或是等级  自己开房的话不会影响其他人

**Comment by FrozenFish259** [comment]
自动开始游戏已经在研究了，暂时没有结果。反挂机检测明天会顺便看一下

**Comment by Cuiyim** [comment]
我目前用的笨办法  鼠标宏每五秒点一次那个坐标位置
