### ISSUE TITLE
特殊角色-无CD是假的!

### ISSUE THREAD

**Issue by 5m17h** [Liuhaixv/Goose_Goose_Duck_Hack#184]
又遇到了，如【间谍鸭子】，是假的无限CD，实战中并不能连杀！

还有【炸弹鸭子】无限CD也是假的，仍旧不能连续仍炸弹💣

**Comment by 5m17h** [comment]
再测试了一盘发现【醍醐】连续按空格也没用啊，只能吃一个人，我反复勾选无限CD才小概率再能空格吃第二个人，但之间损失了很多时间，不适合在第一时间吞一群人。


感觉游戏更新后无CD越来越难找了吗？

**Comment by 5m17h** [comment]
再测试了下，很多鸭子都不能无CD了……
实际上仍有CD等待下一个杀人

**Comment by Droid-MAX** [comment]
你应该说这是游戏更新后，修改了这部分的逻辑或游戏机制，而不是辅助程序本身的问题，说是假的我觉得不妥
