### ISSUE TITLE
【恶性bug】自动完成任务准备过快，导致房主无法开始游戏

### ISSUE THREAD

**Issue by Hanamaki99** [Liuhaixv/Goose_Goose_Duck_Hack#188]
游戏内所有人自动完成任务后游戏会有两次回大厅的bug，目前自动准备demo是在第一次返回大厅时准备。
如果房间内所有人都用该demo自动准备+自动任务，那么第二次回大厅时房主无法开始游戏并出现报错。![IMG_20230124_161658.jpg](https://user-images.githubusercontent.com/20702898/214242460-cf661c86-1ff9-4f1d-9f2d-653ff33d1dbc.jpg)

**Comment by 5m17h** [comment]
我是 被踢出游戏的提示

**Comment by 5m17h** [comment]
那是因为用了这软件的，虽然自动准备了，但是没过多久自己就被踢出游戏了的bug

你开了这么多小号成员，最终小号都被踢出去了，所以房间流局

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.7
