### ISSUE TITLE
自动做任务完全不加币 (更新:六人以下房间不加币)

### ISSUE THREAD

**Issue by ProBeekeeper** [Liuhaixv/Goose_Goose_Duck_Hack#189]
应该是游戏更新所导致的问题

**Comment by ProBeekeeper** [comment]
更新:六人以下房间不加币

**Comment by Cuiyim** [comment]
这个我有经验   看看你的房间是不是私密   我测试过私密不加     公开猎鹅5人加

**Comment by zeyusmart** [comment]
> 这个我有经验 看看你的房间是不是私密 我测试过私密不加 公开猎鹅5人加

我刚刚好像没加

**Comment by HHYzZhu** [comment]
你们确定游戏时常打到了1分钟吗
我怀疑你们的时长没有达到显示结算页面的程度
如果连结算页面都没有硬币是不会算的
