### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by tuoluo348** [Liuhaixv/Goose_Goose_Duck_Hack#19]
我在其他作弊软件上看到有一个多开鹅鸭杀的按钮，配合显示身份，多开一个鹅鸭杀进入房间可以看到其他玩家的身份了。
迷雾功能感觉用处不是很大，可以加一个开关来控制。
其他玩家被带刀杀死后可能不会显示哪个玩家是否杀人，可以输出距离死亡玩家最近的几名玩家的名字。
可以加一个类似fps游戏外挂那种射线透视，把其他玩家的线条都连接到自己操控的角色中心上（线条上标记玩家名字），这样看起来更清晰。
如果可以的话，检测其他玩家使用的技能，例如鹈鹕吃人就标记该玩家是鹈鹕，工程师、鸽子、隐身鸭子等角色使用技能就标记出来。
感谢作者。

**Comment by Liuhaixv** [comment]
谢谢提供建议，关于多开可以使用[Sandboxie](https://github.com/sandboxie-plus/Sandboxie)，我这边多开测试的时候都是用这个。
战争迷雾相关开关设置后续会更新，因为我正在开发GUI界面。
关于绘制相关内容会在GUI界面做好之后的后续版本中推出，将包括你提到的功能。

**Comment by FrozenFish259** [comment]
刚才误解了你多开的意思，如果你指的是多开一个程序后配合辅助读取玩家数据的话，目前的解决方案如下：
1. 启动游戏(用于旁观游戏)
2. 启动辅助
3. 通过[Sandboxie](https://github.com/sandboxie-plus/Sandboxie)沙盒运行第二个游戏(用于游玩游戏)

**Comment by rogxo** [comment]
可以试试截包

**Comment by FrozenFish259** [comment]
@rogxo 服务器不向局内玩家发送身份信息

**Comment by bailijerry** [comment]
> @rogxo 服务器不向局内玩家发送身份信息
如果是通过玩家使用技能判定身份呢
