### ISSUE TITLE
自动做任务对于鹅和鸭子的破坏任务同样生效

### ISSUE THREAD

**Issue by pangjiea** [Liuhaixv/Goose_Goose_Duck_Hack#190]
开启自动做任务后，鹅阵营可以秒完成鸭子的破坏任务，即使是喂食神明这种多次的任务同样可以一次完成；
鸭阵营可以在开局就启动破坏任务（个别需要cd，暂未测试无cd对破坏任务是否生效）

**Comment by cnxxz2333** [comment]
无cd对破坏任务无效，这个是服务器计算的cd。
自动完成任务就是完成读取到的所有任务，这当然也包括鸭破坏解锁任务和鹅紧急任务。
