### ISSUE TITLE
关于自动任务 v0.6.4.7

### ISSUE THREAD

**Issue by ZLKZCC** [Liuhaixv/Goose_Goose_Duck_Hack#195]
我开了个5人房 在首次开始游戏后 启动自动任务功能 任务很快就做完了并且有获取扭蛋币 但第二次开始游戏后 任务栏没有显示任何任务(可能是任务做得太快了?) 但我按了F4应该是关闭了功能的 不知道是什么原因导致了这个发生

**Comment by jinhao29** [comment]
关闭功能无效果 开了之后无法关闭 做狼任务容易给发现

**Comment by ZLKZCC** [comment]
> 关闭功能无效果 开了之后无法关闭 做狼任务容易给发现

原来如此
