### ISSUE TITLE
编译哪个文件，兄弟用的什么编译器

### ISSUE THREAD

**Issue by BUCK111111** [Liuhaixv/Goose_Goose_Duck_Hack#198]

**Comment by BUCK111111** [comment]
C:\mingw64\mingw64\bin\cpp.exe -fdiagnostics-color=always -g C:\Users\lenovo\Desktop\Goose_Goose_Duck_Hack-GUI\Client.cpp -o C:\Users\lenovo\Desktop\Goose_Goose_Duck_Hack-GUI\Client.exe
C:\Users\lenovo\Desktop\Goose_Goose_Duck_Hack-GUI\Client.cpp:1:6: warning: #pragma once in main file
    1 | #pragma once
      |      ^~~~
In file included from C:\Users\lenovo\Desktop\Goose_Goose_Duck_Hack-GUI\Client.h:5,
                 from C:\Users\lenovo\Desktop\Goose_Goose_Duck_Hack-GUI\Client.cpp:3:
C:\Users\lenovo\Desktop\Goose_Goose_Duck_Hack-GUI\Class/Game/PlayerController.h:6:9: fatal error: ../Struct/Common.hpp: No such file or directory
    6 | #include"../Struct/Common.hpp"
      |         ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by Cream-Caramel** [comment]
vs

**Comment by BUCK111111** [comment]
谢谢兄弟搞定了，能否开一下延迟做任务的，任务完成得太快了

**Comment by langzyn** [comment]
问一下 我老是./Struct/Common.hpp: No such file or directorygcc报错这个 咋回事

**Comment by langzyn** [comment]
我也是这个问题 咋解决的

**Comment by langzyn** [comment]
"message": "../Struct/Common.hpp: No such file or directory", 请教一下 这个报错咋回事

**Comment by FrozenFish259** [comment]
> "message": "../Struct/Common.hpp: No such file or directory", 请教一下 这个报错咋回事
> 
> 

字面意思，文件找不到，项目解决方案设置有问题
