### ISSUE TITLE
GUI developing 用户界面正在开发中

### ISSUE THREAD

**Issue by Liuhaixv** [Liuhaixv/Goose_Goose_Duck_Hack#20]
I am currently developing GUI on GUI branch, GUI version will be publish in the next release
当前正在开发GUI用户界面，下个版本将更新发行

**Comment by wsxdc123456** [comment]
GREAT！

**Comment by FrozenFish259** [comment]
Currently the GUI part is half done, focusing on some remaining bugs of GUI relating to multi GUI windows now.
GUI界面开发已经完成一半，框架已经建好，正在优先处理关于绘制窗口和菜单窗口未分离导致的鼠标操作不能穿透到游戏中的bug

**Comment by FrozenFish259** [comment]
> Currently the GUI part is half done, focusing on some remaining bugs of GUI relating to multi GUI windows now. GUI界面开发已经完成一半，框架已经建好，正在优先处理关于绘制窗口和菜单窗口未分离导致的鼠标操作不能穿透到游戏中的bug

Bug已修复https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/commit/137e6001213eacc432a3d7935f213117fb3c1c89

**Comment by FrozenFish259** [comment]
Preview
![image](https://user-images.githubusercontent.com/49237108/211670326-d1496887-e805-49b5-bf87-62e5079427b5.png)

**Comment by wsxdc123456** [comment]
老哥你好，穿墙以后开发能改成一键启动或者关闭吗，这样就不用一直按着alt来触发功能

**Comment by FrozenFish259** [comment]
> 老哥你好，穿墙以后开发能改成一键启动或者关闭吗，这样就不用一直按着alt来触发功能

可以，我等会儿就加上这个功能

**Comment by tuoluo348** [comment]
> 预习 ![图片](https://user-images.githubusercontent.com/49237108/211670326-d1496887-e805-49b5-bf87-62e5079427b5.png)

牛逼啊哥哥

**Comment by FrozenFish259** [comment]
> 老哥你好，穿墙以后开发能改成一键启动或者关闭吗，这样就不用一直按着alt来触发功能

![image](https://user-images.githubusercontent.com/49237108/211717164-ef592f1f-3a50-41c7-9644-df1e7aa9b3c3.png)
做好了，已经上线 https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/commit/a78c3ee68954e77e9e8c3aa6330064fbd2575e06

**Comment by wsxdc123456** [comment]
> > 老哥你好，穿墙以后开发能改成一键启动或者关闭吗，这样就不用一直按着alt来触发功能
> 
> ![图像](https://user-images.githubusercontent.com/49237108/211717164-ef592f1f-3a50-41c7-9644-df1e7aa9b3c3.png)做好了，已经上线 [a78c3ee](https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/commit/a78c3ee68954e77e9e8c3aa6330064fbd2575e06)

great great!

**Comment by FrozenFish259** [comment]
GUI version has been released now, you can download and test it
GUI版本已发行，现在已可进行测试
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.5.0

**Comment by FACEDDD** [comment]
查看玩家身份的功能是哪个？

**Comment by FrozenFish259** [comment]
> 查看玩家身份的功能是哪个？

目前有bug，尚未添加到GUI

**Comment by FACEDDD** [comment]
之前的版本是有的吗，我记得好像可以双开实现身份查看的

**Comment by FrozenFish259** [comment]
> 之前的版本是有的吗，我记得好像可以双开实现身份查看的

@FACEDDD 
有的，现在正在完善GUI界面，后面会加上
