### ISSUE TITLE
新版本穿墙失效

### ISSUE THREAD

**Issue by 204065248** [Liuhaixv/Goose_Goose_Duck_Hack#206]
如题

**Comment by FrozenFish259** [comment]
抽空看下碰撞体怎么改，失效是因为上次游戏更新后数据结构变了

**Comment by 204065248** [comment]
> 抽空看下碰撞体怎么改，失效是因为上次游戏更新后数据结构变了

对，我在老家没东西看，打算回去看，找不到就直接暴力搜数据😂

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.5.3
