### ISSUE TITLE
完成任务不结算

### ISSUE THREAD

**Issue by gregma49j** [Liuhaixv/Goose_Goose_Duck_Hack#208]
现版本的自动任务无法结算，原因是开局时间过短，现提出以下意见：
1.开局若干时间（让用户可以调，一般1-2分钟）后开始刷任务
2.开局后随意走动，以防因为长时间不动被提到大厅
希望大佬能修改下，在下感激不尽！

**Comment by hacklinshell** [comment]
3. 再增加一个开局自动传送坐标的功能，比如地下室地图，传送到-6 ， -0.8 这个位置， 这样猎鹅模式，能够自动挂机

**Comment by FrozenFish259** [comment]
> 

没有这个功能需求,而且旁观也能看到你

**Comment by hacklinshell** [comment]
> 

主要用于自动刷任务刷币活动，
