### ISSUE TITLE
最新的重大版本点击minimap地图的传送功能失败

### ISSUE THREAD

**Issue by 5m17h** [Liuhaixv/Goose_Goose_Duck_Hack#213]
最新的重大版本点击minimap地图的传送功能失败，并不能传送

**Comment by 5m17h** [comment]
难道是今早鹅鸭杀也刚更新吗？

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.7.0.2
