### ISSUE TITLE
鹅鸭杀更新后通过沙盒多开看玩家身份不可用？

### ISSUE THREAD

**Issue by Yang-orz** [Liuhaixv/Goose_Goose_Duck_Hack#214]
我的步骤是
启动本体到达主页，启动辅助
然后经过沙盒启动第二个游戏，然后沙盒进入房间开始游戏，辅助会检测到沙盒内的游戏角色
游戏中通过本体进入该房间观战，辅助并没有显示其他玩家身份，如果此时将辅助关闭，分别在本体和沙盒内都打开一个辅助，那么这两个辅助都会识别到沙河内的游戏角色
不知道临时解决方案是不是我理解错了，如有偏差，恳求大佬指正

**Comment by FrozenFish259** [comment]
游戏更新？

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.7.0.2

**Comment by Yang-orz** [comment]
昨天好像就有这个问题，但又成功了一次，所以我想让您看看这个多开方法是不是对的
