### ISSUE TITLE
无法编译 这是什么情况

### ISSUE THREAD

**Issue by Zk1oo** [Liuhaixv/Goose_Goose_Duck_Hack#219]
![image](https://user-images.githubusercontent.com/122437300/215017138-1ab319dd-e355-435d-a5d2-98ce907e9789.png)

**Comment by BUCK111111** [comment]
直接用他们exe文件，不需要用源码自己编译

**Comment by Zk1oo** [comment]
没看到exe文件呀

**Comment by FrozenFish259** [comment]
@Zk1oo https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases

**Comment by ghost** [comment]
C++版本问题，换个gcc试试。或者你在报错的地方加个强制转换
