### ISSUE TITLE
能加一个缩放在里面吗？，就是类似下面链接的功能

### ISSUE THREAD

**Issue by iceinheart** [Liuhaixv/Goose_Goose_Duck_Hack#220]
https://github.com/asd9176506911298/Goose-Goose-Duck-ImGui

**Comment by FrozenFish259** [comment]
相机那个我之前找过，一直没找到

**Comment by FrozenFish259** [comment]
你这是hook函数改的吗？还是写的内存

**Comment by FrozenFish259** [comment]
我服了，你把所有函数原型全放一个头文件里面了吗？我打开你项目电脑卡死了

**Comment by asd9176506911298** [comment]
Call這兩個
設定大小
LocalPlayer_OverrideOrthographicSize
復原
LocalPlayer_ResetOrthographicSize
晚點試試看

**Comment by FrozenFish259** [comment]
嗯，现在在忙添加选择进程的功能，晚点看
