### ISSUE TITLE
[新功能]增加手动选择游戏进程功能

### ISSUE THREAD

**Issue by FrozenFish259** [Liuhaixv/Goose_Goose_Duck_Hack#222]
由于目前多开游戏刷任务的玩家较多，想要软件正确识别到对应游戏只能将两者放在同一沙盒并设置沙盒禁止访问沙盒外进程。
所以这样显得很麻烦，下一次更新将支持手动选择游戏进程，这样就不必再设置沙盒或将两者放在同一环境运行

**Comment by CC-faker** [comment]
选择完新进程功能使用有效，但是之前选择并应用的功能失效了，麻烦解决一下，谢谢。

**Comment by CC-faker** [comment]
选择完新游戏进程 功能使用有效，但是之前选择的进程并应用的功能失效了，麻烦解决一下，谢谢。希望能多个游戏窗口使用脚本。
