### ISSUE TITLE
[BUG]“自动完成任务+自动准备”中自动准备不工作

### ISSUE THREAD

**Issue by ghost** [Liuhaixv/Goose_Goose_Duck_Hack#223]

**Comment by FrozenFish259** [comment]
什么版本

**Comment by FrozenFish259** [comment]
提供复现步骤

**Comment by obtus** [comment]
版本v7.0.2
打开游戏进入房间,勾选 自动完成任务+自动准备或 仅自动准备 无法自动准备
手动点击准备后,不取消勾选状态,准备状态无法取消

**Comment by FrozenFish259** [comment]
> 版本v7.0.2 打开游戏进入房间,勾选 自动完成任务+自动准备或 仅自动准备 无法自动准备 手动点击准备后,不取消勾选状态,准备状态无法取消

你看看现在什么版本了

**Comment by ghost** [comment]
> 提供复现步骤

更新至7.0.4后已正常工作
