### ISSUE TITLE
请问老哥这个该如何运行

### ISSUE THREAD

**Issue by Ecxaq** [Liuhaixv/Goose_Goose_Duck_Hack#24]
![image](https://user-images.githubusercontent.com/120991976/211678192-b6c1e3e5-1a4f-4704-85ea-0443d0f76b87.png)

**Comment by FrozenFish259** [comment]
这是源码，可运行程序会发行在Release中

**Comment by Ecxaq** [comment]
感谢

**Comment by FrozenFish259** [comment]
下个版本会有用户界面，现在游戏还在维护我这边还没法测试，得等明天游戏开服
[GUI更新](https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/issues/20 )
[最新Release](https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/latest)
