### ISSUE TITLE
编译时无法找到各种头文件，怎么解决啊各位大佬

### ISSUE THREAD

**Issue by admin-xpc** [Liuhaixv/Goose_Goose_Duck_Hack#240]
![image](https://user-images.githubusercontent.com/59109756/215260104-36df6d8d-7e11-4532-9dbe-d2ecbd94de8d.png)
每次点击都是这样

**Comment by asd9176506911298** [comment]
你是用Release嗎 我用Debug都會彈出東西 所以都用Release
Release改成左邊那樣試試
![image](https://user-images.githubusercontent.com/35301327/215260475-995f34da-3060-437c-812b-2a50bf256cfd.png)

**Comment by admin-xpc** [comment]
使用的是relese64 ，就是找不到头文件，也都是在一个文件里面

**Comment by asd9176506911298** [comment]
Release的 include directories 有設定嗎 改成跟左邊一樣

**Comment by admin-xpc** [comment]
可以了，已经可以编译了，十分感谢您
