### ISSUE TITLE
希望增加一端控制多个进程的功能

### ISSUE THREAD

**Issue by cerantes** [Liuhaixv/Goose_Goose_Duck_Hack#248]
现在可以选择进程了，那能不能做到同时勾选多个进程一起控制呢，这样刷币就不用一个进程一个辅助了（痛苦面具）
情人节马上要到了，估计情人节也有扭蛋活动……
谢谢作者

**Comment by FrozenFish259** [comment]
由于糟糕的架构设计，软件只能服务一个进程。要是针对多开得大改，没有可能

**Comment by FrozenFish259** [comment]
我能做的也只是加了个切换进程的功能

**Comment by xsshk** [comment]
> 我能做的也只是加了个切换进程的功能

有无可能增加主进程选择项，对非主进程外的各个进程注入一个热键监听，事件对应准备call，热键处于激活状态则循环调用，否则不进行动作。

**Comment by cerantes** [comment]
> 我能做的也只是加了个切换进程的功能
原来如此，那就算了，谢谢作者~
