### ISSUE TITLE
提交一项BUG和建议

### ISSUE THREAD

**Issue by StarryNe** [Liuhaixv/Goose_Goose_Duck_Hack#252]
bug
**统计死亡位置显示不正确**
以前版本中，玩家死亡后，在角色信息里的死亡快照中可以看见玩家死亡前一秒旁边有哪些人，但是在最新的版本0.7.1.2中，只要开饭后，死亡快照的位置就会重置为开饭地点。

建议
玩家死后会显示出死亡快照和死亡时间，但是只要玩家退出游戏后，死亡快照及时间会消失，无法查阅他死前附近有哪些玩家。建议在开局中储存玩家列表，就算有其他玩家退出游戏，也不会自动删除对应玩家的列表。

**Comment by cnxxz2333** [comment]
可以缓存下来，在游戏结束时清除

**Comment by Belowen** [comment]
我也想来提交这个bug，开会时死亡快照会重置到饭堂，期待快速修复捏。

**Comment by FrozenFish259** [comment]
已记录https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/issues/238
