### ISSUE TITLE
新版本没有任何效果

### ISSUE THREAD

**Issue by NDS7EN** [Liuhaixv/Goose_Goose_Duck_Hack#253]
v0.7.1.2)
[v0.7.1](
[v0.7.0.4]
7.03
7.02
以上版本无法使用没有任何效果
试了7.0可以使用

**Comment by FrozenFish259** [comment]
这种问题怎么能问得出来的？

**Comment by FrozenFish259** [comment]
自己看release记录去

**Comment by FrozenFish259** [comment]
游戏更新了你不更新，怎么能有效果?

**Comment by NDS7EN** [comment]
steam检查更新过没有任何更新。2.1600

**Comment by FrozenFish259** [comment]
> steam检查更新过没有任何更新。2.1600

![image](https://user-images.githubusercontent.com/49237108/215321011-d95b650c-2380-4803-9ea6-a84bfb805a49.png)

**Comment by FrozenFish259** [comment]
不清楚，我这边是2.16.01

**Comment by NDS7EN** [comment]
我也不知道。游戏不更新可以继续

> 不清楚，我这边是2.16.01

已经在steam卸载。,重新安装,成功变成 2.1601 THANKS

**Comment by FrozenFish259** [comment]
> 我也不知道。游戏不更新可以继续
> 
> > 不清楚，我这边是2.16.01
> 
> 已经在steam卸载。,重新安装,成功变成 2.1601 THANKS

破steam就是事多，离谱
