### ISSUE TITLE
开尼🐴的挂呢

### ISSUE THREAD

**Issue by s045pd** [Liuhaixv/Goose_Goose_Duck_Hack#254]
好好的技术用在写挂上真是为你感到悲哀
破坏规则玩游戏，有什么意思吗？？？？？？

**Comment by cnxxz2333** [comment]
你可以不用的，你有权选择。
既然他开源出来了不就是想大家合作吗？如果作者想买卡圈钱的也不会在这里写了啊。
现在不也是有反作弊了吗，有些功能不也失效了吗。
你怎么不去骂那些卖挂圈钱的，那些功能更变态更出生。
你不骂他们你骂这个开源的项目作者你什么意思，是不是卖挂的圈不到钱过来泄气了...

**Comment by Liuhaixv** [comment]
这种人没脑子
