### ISSUE TITLE
最新版貌似移速还是没修复

### ISSUE THREAD

**Issue by likangxian1007** [Liuhaixv/Goose_Goose_Duck_Hack#263]

**Comment by asd9176506911298** [comment]
可能忘了把不能勾選用掉
用最新版的源碼編譯可以

**Comment by likangxian1007** [comment]
> 可能忘了把不能勾選用掉 用最新版的源碼編譯可以

还真是，对的。作者看到了可以改下

**Comment by FrozenFish259** [comment]
> > 可能忘了把不能勾選用掉 用最新版的源碼編譯可以
> 
> 
> 
> 还真是，对的。作者看到了可以改下
> 
> 

啥意思..有点没懂

**Comment by likangxian1007** [comment]
> > > 可能忘了把不能勾選用掉 用最新版的源碼編譯可以
> > 
> > 
> > 还真是，对的。作者看到了可以改下
> 
> 啥意思..有点没懂

打包版本不能修改移速（这么晚还不睡，作者辛苦了qwq）
