### ISSUE TITLE
v0.7.x无法正常工作

### ISSUE THREAD

**Issue by CuzWeAre** [Liuhaixv/Goose_Goose_Duck_Hack#268]
v0.7.x全版本仅可以读取到进程并识别游戏运行状态，其他功能无法正常使用（无论是否管理员模式下）。
![image](https://user-images.githubusercontent.com/86909487/215432078-f27f6eb4-9c1e-4f20-8a17-f72c1364628a.png)
v0.6.x可以正常使用未被和谐的功能，如小地图透视、传送、信息面板、死亡快照。
![image](https://user-images.githubusercontent.com/86909487/215430981-44fbcf88-a3bb-4029-a2fc-a32c150857b7.png)
系统环境为win11 22H2 22621.1105 虚拟化关闭 虚拟内核关闭。

希望作者大大解决一下 ☆⌒(*＾-゜)v THX!!

**Comment by CuzWeAre** [comment]
查阅closed issue后发现，系游戏版本更新v2.16.001后新版辅助失效。
游戏旧版本与steam不会推送新版本更新，请在主界面检查自己的游戏版本。
更新方法：[官网](https://gaggle.fun/goose-goose-duck)安装新版本。

**Comment by FrozenFish259** [comment]
之前也有说steam不提示更新游戏，不清楚
