### ISSUE TITLE
死亡位置显示依旧有问题

### ISSUE THREAD

**Issue by StarryNe** [Liuhaixv/Goose_Goose_Duck_Hack#269]
人物显示依旧有问题，死亡位置和地图上显示不一致。我在港口死的，但是地图显示在广场
![image](https://user-images.githubusercontent.com/108735960/215480264-28987ab4-32f4-4fb3-ac20-9c64b1170fd5.png)
![image](https://user-images.githubusercontent.com/108735960/215480277-12ae01a5-b47e-4698-8d81-e2aee8973bb5.png)

**Comment by FrozenFish259** [comment]
初步定位是由于死亡时间排序导致的，下个版本将禁用排序功能
