### ISSUE TITLE
意思新的反作弊出现？？

### ISSUE THREAD

**Issue by likangxian1007** [Liuhaixv/Goose_Goose_Duck_Hack#271]
知道昨天晚上还可以运行，但是现在只要运行游戏和外挂，游戏就会强制退出，并且无法使用外挂。尝试过重启

**Comment by Bitwise294874** [comment]
+1

**Comment by likangxian1007** [comment]
> +1

貌似刚更新，我自己打包也不行。等作者吧qwq（太辛苦了）

**Comment by asd9176506911298** [comment]
應該是遊戲更新
輔助地址沒更新吧

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/issues/273
