### ISSUE TITLE
相机缩放可以配合视野范围

### ISSUE THREAD

**Issue by jinhao29** [Liuhaixv/Goose_Goose_Duck_Hack#274]
GameAssembly.dll+3CDB720+(offset1)b8+0+20+50
这个是视野范围 我用了很多次 提供一个建议 配合去除战争迷雾效果最佳
目前出现的问题是 因为视野范围太大 看见太多玩家 回出现卡顿现象 但是没办法

**Comment by jinhao29** [comment]
相机缩放与去除迷雾可以配合视野范围

**Comment by jinhao29** [comment]
另外问一下up是如何解决更改数值闪退这个问题 我用ce直接改会闪退 （up开放一下微信群 加满了进不去）

**Comment by FrozenFish259** [comment]
因为你改的是fakeValue

**Comment by FrozenFish259** [comment]
另外你说的视野范围我一直都是都有改，你提到的范围过大导致fps显著降低我也知道，所以我改的范围不是很大
