### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by foggy04** [Liuhaixv/Goose_Goose_Duck_Hack#276]
![image](https://user-images.githubusercontent.com/122350121/215701695-2843609a-af1d-47e4-975b-68a4da3372d0.png)

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.7.1.3.3

**Comment by foggy04** [comment]
> https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.7.1.3.3

你的编译环境是什么  链接中的源码下载后编译失败

**Comment by foggy04** [comment]
参考了一下以下问题的回复任然无法运行
![image](https://user-images.githubusercontent.com/122350121/215908202-7818bf8c-4ea3-404c-8968-6d7c2dc49b1a.png)

![image](https://user-images.githubusercontent.com/122350121/215908067-4028e738-8127-43b3-b0eb-9e73ea231445.png)
