### ISSUE TITLE
大佬，新版本移除技能冷却时间功能不可选。

### ISSUE THREAD

**Issue by julyC31** [Liuhaixv/Goose_Goose_Duck_Hack#277]

**Comment by likangxian1007** [comment]
你觉得为什么不可以

**Comment by julyC31** [comment]
> 你觉得为什么不可以

那是什么情况呢？我不知道

**Comment by cnxxz2333** [comment]
> > 你觉得为什么不可以
> 
> 那是什么情况呢？我不知道

冷却时间已经是服务端计算的了，也可能是本地数据加密了，所以暂时用不了，这个issues可以close了。

**Comment by FrozenFish259** [comment]
@likangxian1007 笑死我了你们，2楼你这话我不说过一次吗

**Comment by likangxian1007** [comment]
> @likangxian1007 笑死我了你们，2楼你这话我不说过一次吗

对呀哈哈哈哈哈哈，对我说的qwq

**Comment by FrozenFish259** [comment]
@likangxian1007 
![}7ZGTG9L0VD23Y O@33FD6](https://user-images.githubusercontent.com/49237108/215802090-876cdb70-38a6-4fa6-8a69-bed52aa4e222.gif)
