### ISSUE TITLE
游戏显示未运行  看不到玩家数量   不能够自动完成任务

### ISSUE THREAD

**Issue by XhyJo** [Liuhaixv/Goose_Goose_Duck_Hack#281]
![image](https://user-images.githubusercontent.com/124039643/215926731-ce7d3323-c8ec-440c-b08f-16fe70ce4f86.png)
我是一个萌新  不会用这些   或许安装位置有错误？或者解压方式不对？ 微信群满了   求助不了  只好到这里求助一下了 有大佬帮忙一下吗

**Comment by ThreeNightmare** [comment]
是否按照运行须知以管理员权限运行

**Comment by badhhui** [comment]
游戏和辅助的版本对不上，试试把游戏和辅助都更新到最新版

**Comment by XhyJo** [comment]
是按照管理员权限运行的　　　辅助和游戏也是最新版本

**Comment by zuoercc** [comment]
用旧版鹅鸭杀

**Comment by FrozenFish259** [comment]
![image](https://user-images.githubusercontent.com/49237108/216077679-bcfc5b94-f232-4720-9d39-f8840478c6e2.png)
![image](https://user-images.githubusercontent.com/49237108/216077728-62e1438b-8db7-42b1-a3f3-84c1a787d9cf.png)
