### ISSUE TITLE
希望作者大大能一直完善防封禁功能

### ISSUE THREAD

**Issue by RoyMoqqq** [Liuhaixv/Goose_Goose_Duck_Hack#298]
因为在某宝上购买到了黑金，然后又在本号上充值了很多钱，不想让自己的号废掉

**Comment by 5m17h** [comment]
那你别开挂不就行了

更新最快的永远是游戏工作室

**Comment by RoyMoqqq** [comment]
> 那你别开挂不就行了
> 
> 更新最快的永远是游戏工作室

我不是开挂被封号的，在某宝买到了黑金。

**Comment by blue-chocolates** [comment]
信用卡欺骗了官方本就形成利益挂钩，个人造成问题不给予解决
