### ISSUE TITLE
Any chance to solve this next update??? Windows 7 black window

### ISSUE THREAD

**Issue by pharita123** [Liuhaixv/Goose_Goose_Duck_Hack#304]
the game is glitching here on windows 10 in this new update, so i came back to windows 7 to play again
but dont work here with black screen

![Untitled 2](https://user-images.githubusercontent.com/124131866/217986491-ffa975e9-0a90-4ab0-86a2-fe5088174603.jpg)

**Comment by FrozenFish259** [comment]
Only works on win10 or win11
