### ISSUE TITLE
群聊进不去

### ISSUE THREAD

**Issue by Infullcharge** [Liuhaixv/Goose_Goose_Duck_Hack#308]

**Comment by FrozenFish259** [comment]
https://raw.githubusercontent.com/Liuhaixv/Goose_Goose_Duck_Hack/GUI/img/wechat_group9.jpg

**Comment by Carolmelon** [comment]
> https://raw.githubusercontent.com/Liuhaixv/Goose_Goose_Duck_Hack/GUI/img/wechat_group9.jpg

二维码又过期了

**Comment by FrozenFish259** [comment]
Q群
