### ISSUE TITLE
无法启动，替换ddl以后，点击GGDLauncher.exe

### ISSUE THREAD

**Issue by Carolmelon** [Liuhaixv/Goose_Goose_Duck_Hack#310]
提示unknown file version，如图
![unknown file version](https://user-images.githubusercontent.com/24358002/218138389-a30e0010-03c6-47dc-87bd-50e51b4a8b3e.png)

**Comment by FrozenFish259** [comment]
EAC覆盖文件关掉

**Comment by Carolmelon** [comment]
好的，之前的版本我没用过，刚刚下了个旧版看到里面的用法了

**Comment by AndyBBBB** [comment]
怎么关掉EAC覆盖文件
