### ISSUE TITLE
替换dll了，请问怎么注入？我真是不太会

### ISSUE THREAD

**Issue by AndyBBBB** [Liuhaixv/Goose_Goose_Duck_Hack#312]
您好，我替换dll了，但请问怎么注入？我真是不太会。希望可以解答我这个“弱智问题”。感激不尽。

**Comment by FrozenFish259** [comment]
看说明，覆盖文件就可以，没有所谓的注入，那都是骗小孩的

**Comment by AndyBBBB** [comment]
说明中说“替换根目录同名dll 本方法基本不会失效”，现在我替换了，但是进入游戏就提示我“应用程序无法正常启动”。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月11日(周六) 中午12:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] 替换dll了，请问怎么注入？我真是不太会 (Issue #312)




 
看说明，覆盖文件就可以，没有所谓的注入，那都是骗小孩的

**Comment by FrozenFish259** [comment]
我哪里写要替换dll了

**Comment by FrozenFish259** [comment]
你说的那个是多开的工具

**Comment by AndyBBBB** [comment]
我只是想知道怎么使用该作弊程序😢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月11日(周六) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] 替换dll了，请问怎么注入？我真是不太会 (Issue #312)




 
你说的那个是多开的工具

**Comment by AndyBBBB** [comment]
现在我既没法开外挂玩，也没法正常玩，因为替换了dll文件，应用程序无法正常启动😢😢😢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月11日(周六) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] 替换dll了，请问怎么注入？我真是不太会 (Issue #312)




 
你说的那个是多开的工具

**Comment by AndyBBBB** [comment]
我好像知道了……我以为是外挂要求我替换dll……所以怎么使用您的外挂？我没有在文件夹“GGD Hack”中找到任何应用程序，只有一些图片或文本。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月11日(周六) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] 替换dll了，请问怎么注入？我真是不太会 (Issue #312)




 
你说的那个是多开的工具
