### ISSUE TITLE
群二维码过期，辅助闪退求解

### ISSUE THREAD

**Issue by haihan99** [Liuhaixv/Goose_Goose_Duck_Hack#318]
你好 请问辅助打开后闪退 是为什么呀 我看到上个版本更新写的运行 GGDlauncher.exe 不能运行 goosegooseduck.exe这两个程序是指游戏程序还是辅助程序的名字？辅助程序在最新的压缩包中只有goosegooseduck.exe　没有GGDlauncher.exe

**Comment by cnxxz2333** [comment]
他的意思是多开游戏要运行游戏目录里面的ggdluncher，打开辅助闪退检查下辅助的权限之类的

**Comment by haihan99** [comment]
> 他的意思是多开游戏要运行游戏目录里面的ggdluncher，打开辅助闪退检查下辅助的权限之类的

明白了，请问辅助闪退一般情况下是哪里出现了问题呢，软件可以使用穿墙那些　但是大概二十秒闪退　给个管理员权限运行

**Comment by cnxxz2333** [comment]
> > 他的意思是多开游戏要运行游戏目录里面的ggdluncher，打开辅助闪退检查下辅助的权限之类的
> 
> 明白了，请问辅助闪退一般情况下是哪里出现了问题呢，软件可以使用穿墙那些　但是大概二十秒闪退　给个管理员权限运行

emm，这个情况我没碰见，我也不清楚
