### ISSUE TITLE
替换多开用的“UnityPlayer.dll”文件后提示错误无法启动游戏

### ISSUE THREAD

**Issue by icer233** [Liuhaixv/Goose_Goose_Duck_Hack#319]
替换多开用的“UnityPlayer.dll”文件后提示错误无法启动游戏
错误提示：

![微信图片_20230211203220](https://user-images.githubusercontent.com/74440627/218258145-acb3b329-bd9d-4026-aa68-ae58f05e4159.png)

**Comment by FrozenFish259** [comment]
修改EAC的settings文件
