### ISSUE TITLE
游戏中EAC貌似加强了，会检测EAC是否运行

### ISSUE THREAD

**Issue by Carolmelon** [Liuhaixv/Goose_Goose_Duck_Hack#325]
游戏中突然报错EAC missing，害怕，可能会被封号了
![image](https://user-images.githubusercontent.com/24358002/218274053-2766ea85-b3e7-42a5-94de-51093423d990.png)

**Comment by FrozenFish259** [comment]
网络问题，和EAC没关系

**Comment by FrozenFish259** [comment]
大概率是游戏卡住了，所以和EAC的通讯未响应
