### ISSUE TITLE
找不到imgui.h怎样解决

### ISSUE THREAD

**Issue by Zk1oo** [Liuhaixv/Goose_Goose_Duck_Hack#33]
找不到imgui.h怎样解决

**Comment by Zk1oo** [comment]
谢谢

**Comment by Zk1oo** [comment]
我是新手，请问将此行代码添加到哪里？

**Comment by Stevenhake** [comment]
你哪里报错就替换他

**Comment by Zk1oo** [comment]
替换后他提示

**Comment by Zk1oo** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2006	“#include”: 应为 "FILENAME" 或 <FILENAME>	GooseGooseDuckHack	C:\Users\池永泽\Desktop\Goose_Goose_Duck_Hack-GUI\UI.h	9	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E1696	无法打开 源 文件 "imgui_impl_dx11.h"	GooseGooseDuckHack	C:\Users\池永泽\Desktop\Goose_Goose_Duck_Hack-GUI\UI.h	11	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E0013	应输入文件名	GooseGooseDuckHack	C:\Users\池永泽\Desktop\Goose_Goose_Duck_Hack-GUI\UI.h	9	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “”: No such file or directory	GooseGooseDuckHack	C:\Users\池永泽\Desktop\Goose_Goose_Duck_Hack-GUI\UI.h	9

**Comment by Zk1oo** [comment]
替换后他提示这些错误

**Comment by Zk1oo** [comment]
![image](https://user-images.githubusercontent.com/122437300/211833394-3661d49b-a217-47ac-9bc6-2598ccf40c06.png)

**Comment by FrozenFish259** [comment]
#22

**Comment by FrozenFish259** [comment]
重新下载下GUI分支的源码打开项目，因为我之前项目里面include ImGui用的是绝对路径，所以你们那边都会报错。我改成相对路径了
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/commit/c23403d5404448e5329574b2ac33b29502c62fde

**Comment by Stevenhake** [comment]
你新建个筛选器，把文件的imgui所有文件给拉进去就可以了

**Comment by Zk1oo** [comment]
![image](https://user-images.githubusercontent.com/122437300/211845336-f790cdb2-ab01-450d-b9b5-fa1ee18e0a80.png)
这是咋了

**Comment by Stevenhake** [comment]
用release编译

**Comment by FrozenFish259** [comment]
@Zk1oo 不要用Debug模式编译，用Release x64， 因为我用的ImGui是最新的测试版本，用debug会报很多异常的
