### ISSUE TITLE
你能制作除服装模式以外的版本吗?

### ISSUE THREAD

**Issue by wooper714** [Liuhaixv/Goose_Goose_Duck_Hack#345]
可能是因为有服装模式,很难利用我收集的制鞋或掌握我的服装。
在服装模式因更新等而受阻之前,想获得可以获得的服装,但由于是模式,所以很难确认。
出于这个原因，我想知道是否可以提供排除服装模式的模式。

**Comment by FrozenFish259** [comment]
好
