### ISSUE TITLE
希望作者解决衣服闪掉问题

### ISSUE THREAD

**Issue by 1635837483** [Liuhaixv/Goose_Goose_Duck_Hack#346]
![Screenshot_20230306_134418_org kuyo game](https://user-images.githubusercontent.com/127079253/223031375-0415df06-52be-4ac9-afac-ad291514df16.jpg)
![Screenshot_20230306_134402_org kuyo game](https://user-images.githubusercontent.com/127079253/223031378-80f6d63b-b545-4c9d-b7e1-72b35d8abf57.jpg)

**Comment by FrozenFish259** [comment]
服务器强制刷新，无法解决

**Comment by 1635837483** [comment]
之前我用官方版我自己的衣服也出现了闪退问题然后过两天就好了不知道咋回事
