### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by F4nX1ngCN** [Liuhaixv/Goose_Goose_Duck_Hack#35]
1. 启动后SpeedHack修改移速功能默认数值为0 无法移动 需要手动拉回默认数值
2. 无身份显示 后续可以进行完善

**Comment by FACEDDD** [comment]
游戏不是维护了吗，身份显示的话是如何操作的？

**Comment by FrozenFish259** [comment]
嗯，这几天游戏维护了我就一直在做GUI，毕竟没法测试

**Comment by FrozenFish259** [comment]
Issue #32
