### ISSUE TITLE
Add a map that shows all players' positions

### ISSUE THREAD

**Issue by FrozenFish259** [Liuhaixv/Goose_Goose_Duck_Hack#39]
添加一个显示所有玩家位置的地图

**Comment by FrozenFish259** [comment]
Player can teleport to the point where clicked on the map too
可以通过点击地图来传送到对应位置

**Comment by wsxdc123456** [comment]
完美的

**Comment by lanting200** [comment]
这个地图可以支持右键传送的话就更好了

**Comment by FrozenFish259** [comment]
> 这个地图可以支持右键传送的话就更好了

好的，谢谢建议

**Comment by FrozenFish259** [comment]
Early preview
早期预览效果
![image](https://user-images.githubusercontent.com/49237108/212007023-bbd84f11-2c41-4ab0-a78b-c9ec0c5ceedc.png)

**Comment by F4nX1ngCN** [comment]
反馈: 无法显示玩家位置 以及无法右键传送

**Comment by FrozenFish259** [comment]
> 反馈: 无法显示玩家位置 以及无法右键传送

功能还未推出，当前仍在测试

**Comment by F4nX1ngCN** [comment]
> > 反馈: 无法显示玩家位置 以及无法右键传送
> 
> 功能还未推出，当前仍在测试

了解
