### ISSUE TITLE
0.5.3 游戏已更新，hack不工作

### ISSUE THREAD

**Issue by wsxdc123456** [Liuhaixv/Goose_Goose_Duck_Hack#41]
1. 启动游戏，然后启动hack，hack出现闪退，再双击应用无反应.
2. 关闭游戏，先启动hack，再启动游戏，hack不工作.

**Comment by FrozenFish259** [comment]
这个bug应该已经修复了，稍后我发布下更新

**Comment by imutum** [comment]
穿墙，迷雾，移速，都可以工作，但是角色信息里全为空
![image](https://user-images.githubusercontent.com/50545012/211956313-36d2defa-98bd-4dee-820f-14a797c921fd.png)

**Comment by FrozenFish259** [comment]
> 穿墙，迷雾，移速，都可以工作，但是角色信息里全为空 ![image](https://user-images.githubusercontent.com/50545012/211956313-36d2defa-98bd-4dee-820f-14a797c921fd.png)

正在弄，主要是汉字不好处理，要费点时间

**Comment by wsxdc123456** [comment]
很nice
