### ISSUE TITLE
I hope to learn from you

### ISSUE THREAD

**Issue by blue-chocolates** [Liuhaixv/Goose_Goose_Duck_Hack#43]
I hope to learn from you. If you have contact information, please let me know.

**Comment by wsxdc123456** [comment]
Same, but I don't know how to program, I can only be a tester

**Comment by blue-chocolates** [comment]
> Same, but I don't know how to program, I can only be a tester

I wrote a cheat using Python, but I will not find the offset address

**Comment by FrozenFish259** [comment]
qq1244653065
