### ISSUE TITLE
这个全局光源的问题会影响游戏语音声音的位置，有几率触发没有语音声音

### ISSUE THREAD

**Issue by wuquanzhao** [Liuhaixv/Goose_Goose_Duck_Hack#5]

**Comment by Liuhaixv** [comment]
谢谢提出这个问题，我之前没注意到。下个版本这个问题就会被修复，将使用新方法去除战争迷雾

**Comment by Liuhaixv** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.3.1
