### ISSUE TITLE
角色信息偶尔显示不出来，只能显示一部分玩家，游戏返回主菜单有时候游戏会崩溃

### ISSUE THREAD

**Issue by heixiu03** [Liuhaixv/Goose_Goose_Duck_Hack#51]

**Comment by F4nX1ngCN** [comment]
![image](https://user-images.githubusercontent.com/78652221/212020006-702e7d7d-8092-4d85-a419-4a45aacb5fde.png)

**Comment by F4nX1ngCN** [comment]
无身份信息

**Comment by F4nX1ngCN** [comment]
同时本轮杀过人也有问题

**Comment by heixiu03** [comment]
> 同时本轮杀过人也有问题
看文档，这个暂时无法修复

**Comment by F4nX1ngCN** [comment]
> > 同时本轮杀过人也有问题
> > 看文档，这个暂时无法修复

了解

**Comment by wsxdc123456** [comment]
问一下，0.5.5.1版本的minimap有什么用，这种小问题就不开issue了

**Comment by heixiu03** [comment]
> 问一下，0.5.5.1版本的minimap有什么用，这种小问题就不开issue了

暂时用不了应该

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.2.4
