### ISSUE TITLE
最新版的扩展小地图传送点击后无反应

### ISSUE THREAD

**Issue by 5m17h** [Liuhaixv/Goose_Goose_Duck_Hack#57]
最新版的扩展小地图传送点击后无反应
没删地图，都正常加载的minimap，透视是能透视所有玩家坐标，但是我左右键点击地图后并没传送成功

**Comment by wsxdc123456** [comment]
小地图占用画面太大了，等待作者增加缩放功能

**Comment by FrozenFish259** [comment]
传送功能还没添加, 现在放出来只是测试下看看有没有bug，现在我正在优先处理小地图窗口的缩放问题

**Comment by FrozenFish259** [comment]
@wsxdc123456 https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.1
