### ISSUE TITLE
可以添加 一个技能无cd功能

### ISSUE THREAD

**Issue by Zk1oo** [Liuhaixv/Goose_Goose_Duck_Hack#58]
可以添加 一个技能无cd功能 使用带技能的角色时有更好的体验

**Comment by FrozenFish259** [comment]
嗯，后续会添加
Issue #34

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.2.5
