### ISSUE TITLE
minimap无法工作

### ISSUE THREAD

**Issue by white-and-white** [Liuhaixv/Goose_Goose_Duck_Hack#60]
运行后minimap界面仍为0*0，没有显示任何图片

**Comment by FrozenFish259** [comment]
看下img文件夹在不在

**Comment by white-and-white** [comment]
img文件在，而且我大概看了下代码，感觉也没什么问题

**Comment by FrozenFish259** [comment]
现在正常工作吗?

**Comment by white-and-white** [comment]
我去试下


从 Windows 版邮件发送

发件人: Liuhaixv
发送时间: 2023年1月13日 16:47
收件人: Liuhaixv/Goose_Goose_Duck_Hack
抄送: slzmnb; Author
主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] minimap无法工作 (Issue #60)

现在正常工作吗?

**Comment by white-and-white** [comment]
2023/1/13 17:00
版本0.6.2.2
Minimap仍旧无法正常工作
附件内容为minimap的界面
或许修改视距并添加射线方框比minimap更好？我无法确定

从 Windows 版邮件发送

发件人: Liuhaixv
发送时间: 2023年1月13日 16:47
收件人: Liuhaixv/Goose_Goose_Duck_Hack
抄送: slzmnb; Author
主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] minimap无法工作 (Issue #60)

现在正常工作吗?

**Comment by FrozenFish259** [comment]
目前没有人反馈过这个问题，你能截图下exe程序的同级目录文件夹吗

**Comment by white-and-white** [comment]
从 Windows 版邮件发送

发件人: Liuhaixv
发送时间: 2023年1月13日 17:10
收件人: Liuhaixv/Goose_Goose_Duck_Hack
抄送: slzmnb; Author
主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] minimap无法工作 (Issue #60)

目前没有人反馈过这个问题，你能截图下exe程序的同级目录文件夹吗

**Comment by FrozenFish259** [comment]
> 从 Windows 版邮件发送 发件人: Liuhaixv 发送时间: 2023年1月13日 17:10 收件人: Liuhaixv/Goose_Goose_Duck_Hack 抄送: slzmnb; Author 主题: Re: [Liuhaixv/Goose_Goose_Duck_Hack] minimap无法工作 (Issue #60) 目前没有人反馈过这个问题，你能截图下exe程序的同级目录文件夹吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你邮件发的东西我这边收不到，邮箱也看不到

**Comment by white-and-white** [comment]
![dir](https://user-images.githubusercontent.com/95952545/212283079-6d4f4504-822e-4fff-bc8e-a45855105461.png)

**Comment by FrozenFish259** [comment]
> ![dir](https://user-images.githubusercontent.com/95952545/212283079-6d4f4504-822e-4fff-bc8e-a45855105461.png)

你这里没有img文件夹啊

**Comment by FrozenFish259** [comment]
地图图片是从同级目录下的img文件夹里的maps文件夹中读取的

**Comment by white-and-white** [comment]
好的
