### ISSUE TITLE
[Suggestion]能否将本地玩家坐标与其他玩家坐标在一页中显示

### ISSUE THREAD

**Issue by pangjiea** [Liuhaixv/Goose_Goose_Duck_Hack#63]
或通过完善minimap来提供相对位置的参考，以便寻找其他玩家

**Comment by pangjiea** [comment]
我认为可以考虑在第二页中加入本地玩家信息

**Comment by FrozenFish259** [comment]
minimap现在将本地玩家和其他玩家的颜色区分开来了

**Comment by FrozenFish259** [comment]
![image](https://user-images.githubusercontent.com/49237108/212275242-984627d1-7732-490b-8038-3fe29f38ad41.png)
