### ISSUE TITLE
简单的添加地图按键开关 和 默认窗口大小

### ISSUE THREAD

**Issue by lanting200** [Liuhaixv/Goose_Goose_Duck_Hack#69]
![image](https://user-images.githubusercontent.com/42830954/212244950-5f909eb0-6595-48a4-ae1c-e516b40b82ba.png)
![image](https://user-images.githubusercontent.com/42830954/212244974-2beaf36a-e2ca-4105-a6ee-f8eaedb8df16.png)
![image](https://user-images.githubusercontent.com/42830954/212245030-0a11d3c8-2c59-407c-96c3-c27c99f1535b.png)
![image](https://user-images.githubusercontent.com/42830954/212245069-a9f39ebf-2bc7-4642-b43c-39579b962c6d.png)
![image](https://user-images.githubusercontent.com/42830954/212245099-38691f82-5e86-41c0-895f-f2361055ac0a.png)

**Comment by FrozenFish259** [comment]
很好

**Comment by FrozenFish259** [comment]
可以创建PR请求，我会合并

**Comment by lanting200** [comment]
第一次发布请求 额是不是这样搞

**Comment by lanting200** [comment]
这个应该可以关了

**Comment by FrozenFish259** [comment]
谢谢贡献代码
