### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by xia0bai** [Liuhaixv/Goose_Goose_Duck_Hack#7]
在未进入房间的情况下程序正常运行；
在进入房间后打开程序会直接闪退

测试场景：
1. 打开Goose Goose Duck
2. 打开程序（此时程序正常运行）
3. 点击开始游戏，并进入房间，进入房间后程序闪退
4. 重新打开程序，闪退

**Comment by wuquanzhao** [comment]
可以试试管理员身份打开

**Comment by xia0bai** [comment]
> 可以试试管理员身份打开

是使用管理员身份打开的，系统信息：Windows 11 Pro 22H2  22621.963

**Comment by xia0bai** [comment]
再次进行尝试没有发现问题，不太清楚之前闪退是何原因，可能有什么进程导致的

**Comment by Liuhaixv** [comment]
因为我写的代码太烂了，很正常

**Comment by Liuhaixv** [comment]
我乱改数据的时候就会闪退，不过正常运行的时候没出现过这个问题，重启游戏应该可以解决

**Comment by Liuhaixv** [comment]
这个问题应该是因为我之前用错了读内存的函数，现在崩溃的概率应该会小一些
