### ISSUE TITLE
有时退回主菜单时会报错

### ISSUE THREAD

**Issue by imutum** [Liuhaixv/Goose_Goose_Duck_Hack#71]
![image](https://user-images.githubusercontent.com/50545012/212248128-8a9fe35a-6b56-40ea-a06c-e4eb8ccffe41.png)

**Comment by FrozenFish259** [comment]
这个问题我也注意到了，目前发现是由于更新玩家姓名导致的内存溢出问题，后面会修复

**Comment by wsxdc123456** [comment]
是的我也经常遇到这个问题，还以为是自己程序出错了

**Comment by FrozenFish259** [comment]
BUG复现:
1. 运行辅助
2. 打开游戏
3. 选择教程，选择地下室地图进行游戏
4. 游戏崩溃
5. 辅助因为程序崩溃导致内存溢出也接着崩溃

**Comment by Liuhaixv** [comment]
初步定位问题可能的位置
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/blob/4ef481b1757542fdce0dc18bd1f22584518d0e3c/Class/DataUpdater.hpp#L38

**Comment by FrozenFish259** [comment]
Bug已经定位成功，是由于线程更新玩家的碰撞箱导致的游戏内存溢出问题, 下个版本将修复

**Comment by FrozenFish259** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.6.2.4
