### ISSUE TITLE
0.31 version

### ISSUE THREAD

**Issue by wooper714** [Liuhaixv/Goose_Goose_Duck_Hack#8]
Hello, I tested the 0.31 version.
But if I turn off the light, I can't see the character's name.
Is it possible to edit it?

**Comment by wooper714** [comment]
In addition, it seems that the "KILLED THIS ROUND," which allows you to check if someone else killed you on this turn when you are alive, is not confirmed.

**Comment by Liuhaixv** [comment]
Thanks for the reply, informations like rolenames and "killed this round" are hidden if you are ingame player. I am still working on it.
Issue #3
