### ISSUE TITLE
游戏中启动辅助 地图才能取到玩家位置 这个可以修复嘛

### ISSUE THREAD

**Issue by FrozenFish259** [Liuhaixv/Goose_Goose_Duck_Hack#84]
游戏中启动辅助 地图才能取到玩家位置 这个可以修复嘛

_Originally posted by @lanting200 in https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/issues/83#issuecomment-1381610199_

**Comment by lanting200** [comment]
我认为可以做个初始化按键 进游戏点击初始化初步解决这个问题 

理想状态还是程序自动可以取到游戏状态自动初始化

**Comment by FrozenFish259** [comment]
> 我认为可以做个初始化按键 进游戏点击初始化初步解决这个问题
> 
> 理想状态还是程序自动可以取到游戏状态自动初始化

Bug已经定位到了，是因为有个函数只在构造函数里面执行一次，导致了有变量在游戏启动后没有初始化
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/commit/e50428bb035e497b36408fe96fb4e38b3b9c7669

**Comment by lanting200** [comment]
了解
