### ISSUE TITLE
希望新增一键完成任务和在房间内自动准备的功能

### ISSUE THREAD

**Issue by Erazul** [Liuhaixv/Goose_Goose_Duck_Hack#89]
我只想刷一些和横幅还有背景成就，希望增加一个点击任务自动完成的功能，还有一个在其他人准备开始游戏阶段能自动准备的功能。多谢

**Comment by aks-ky** [comment]
用手柄玩的话做任务只要一直按A就可以

程序可以尝试模拟手柄按键
