### ISSUE TITLE
帧率有点卡，可以按需要修复，职业显示优先级别较高

### ISSUE THREAD

**Issue by wuquanzhao** [Liuhaixv/Goose_Goose_Duck_Hack#9]

**Comment by Liuhaixv** [comment]
这个问题可能是因为移除战争迷雾导致的，因为玩家的视野范围调大了。关于职业身份和其他的一些信息我还在想办法获取
Issue #3

**Comment by Liuhaixv** [comment]
https://github.com/Liuhaixv/Goose_Goose_Duck_Hack/releases/tag/v0.3.3
